### ISSUE TITLE
How do I know if it's working? Nothing in the Table

### ISSUE THREAD

**Issue by Fogest** [mgnsk/FreshRSS-AutoTTL#16]
Please see attached image. When I look at the extension options, the table that I think should list information about the AutoTTL is empty. I have some old errors from some days back in the FreshRSS logs, but that may have been related to a permission issue that I think I have resolved. 

![image](https://github.com/user-attachments/assets/fcae4c17-5cb9-4e9f-9fd0-7837aedcf8f7)

Is there any way I could provide you more information regarding the issue to help determine what might be the issue? I can turn up debugging but I don't know if there is anyway to force it to run or something? 

Here are the log messages I am no longer getting after some permission fixes:
![image](https://github.com/user-attachments/assets/e60bba05-9c05-4ea9-ac47-7dfbd9f66d03)

And here are some permission screenshots in case it helps

![image](https://github.com/user-attachments/assets/b46a8118-bb0d-4a63-b7b8-849c6e596491)

From my understanding I have done everything correctly. My FreshRSS refresh default time is set to 1 hour. All my feeds are set to use the default, and AutoTTL I set to 12 hour max TTL.

**Comment by mgnsk** [comment]
Which database are you using?

**Comment by mgnsk** [comment]
I've reproduced the empty table issue, looking into it. FreshRSS seems to have changed the way extension's `init` functions work.

**Comment by mgnsk** [comment]
Fixed in https://github.com/mgnsk/FreshRSS-AutoTTL/releases/tag/v0.5.7.

**Comment by Fogest** [comment]
I updated and still don't notice anything in the table. I don't see any new entries in the logs with the new updates. I am using MySQL for my database.

**Comment by mgnsk** [comment]
> I updated and still don't notice anything in the table. I don't see any new entries in the logs with the new updates. I am using MySQL for my database.

Do you see any errors in Apache logs?

**Comment by mgnsk** [comment]
I've fixed a looming configuration issue and tested with every database in [v0.5.8](https://github.com/mgnsk/FreshRSS-AutoTTL/releases/tag/v0.5.8). Don't know what else to look for.

**Comment by Fogest** [comment]
The latest updates fixed this, I see the table with data now :). 

Thanks for the fix!
